const PREFIX = 'md-reader__'
const p = ([block]: TemplateStringsArray) => PREFIX + block

export default {
  PREFIX,
  MD_BODY: p`body`,
  MD_SIDE: p`side`,
  MD_SIDE_ACTIVE: p`side-li--active`,
  MD_SIDE_TABS: p`side-tabs`,
  MD_SIDE_TAB: p`side-tab`,
  MD_SIDE_TAB_ACTIVE: p`side-tab--active`,
  MD_SIDE_PANELS: p`side-panels`,
  MD_SIDE_PANEL: p`side-panel`,
  MD_SIDE_PANEL_ACTIVE: p`side-panel--active`,
  MD_SIDE_LIST: p`side-list`,
  MD_SIDE_HEAD: p`side-head`,
  MD_SIDE_HEAD_TITLE: p`side-head-title`,
  MD_SIDE_BACK: p`side-back`,
  MD_SIDE_FILE: p`side-file`,
  MD_SIDE_FILE_DIR: p`side-file--dir`,
  MD_SIDE_FILE_ACTIVE: p`side-file--active`,
  MD_SIDE_ENTRY: p`side-entry`,
  MD_SIDE_EMPTY: p`side-empty`,
  MD_SIDE_HISTORY_ITEM: p`side-history`,
  MD_SIDE_HISTORY_TEXT: p`side-history-text`,
  MD_SIDE_HISTORY_NAME: p`side-history-name`,
  MD_SIDE_HISTORY_PATH: p`side-history-path`,
  MD_SIDE_FOLDER_BTN: p`side-folder-btn`,
  MD_CONTENT: p`markdown-content`,
  MD_BUTTON: p`btn`,
  HEAD_ANCHOR: p`head-anchor`,
  BUTTON_WRAP_ELE: p`button-wrap`,
  CODE_TOGGLE_BTN: p`btn--code-toggle`,
  SIDE_EXPAND_BTN: p`btn--side-expand`,
  GO_TOP_BTN: p`btn--go-top`,
  COPY_BTN: p`btn--copy`,
  SIDE_COLLAPSED: 'side-collapsed',
  SIDE_EXPANDED: 'side-expanded',
  MODAL: p`modal`,
  ZOOM_IMAGE: p`zoom-image`,
}
